### ISSUE TITLE
Recipe: Minimal Titlebar, Almost No Titlebar

### ISSUE THREAD

**Issue by skylize** [sindrets/atom-title-bar-replacer#15]
Just want to document this for other users who want "no titlebar". I worked up a style that reduces this custom titlebar to a mere 6px tall with tiny buttons and no pathname/title. 

This gives the best of both worlds between having or not having a titlebar. You still have a 6px tall area at the top of the window for dragging the window around, and buttons available for minimize/maximize/close when your hand is already on the mouse. 

(With the most recent 1.6.1 update the `Alt` key menu will cleanly auto-expand, pushing the editor downward to make room for the menu.) 

This is written for version 1.6.1, which changed the classnames from previous versions. 

1. Install the package and remove the window frame by selecting the `Remove Window Frame` option in the Settings panel.

1. Type `Ctrl`-`Shift`-`P` --> `stylesheet`. Choose `Application: Open Your Stylesheet` from the Command Palette.

1. Add the following styles to your `styles.less` file and save:

```css
.title-bar-replacer {
  .tbr-title-bar {
    height: 6px;
  }

  .custom-title {
    display: none;
  }

  .material-icons{
    margin: 0;
    padding: 0 3px;
    font-size: 9px;
    // top: -11px;
  }
  
  .material-icons:hover:before {
    width: 12px;
    height: 9px;
    top: 0px;
    left: 1.4px;
    border-radius: 2.5px;
    background-color: @bright;
  }
}
```

**Comment by skylize** [comment]
Theoretically this shouldn't be needed any more because v1.7.0 adds a Compact mode that should handle it under the hood. Unfortunately Compact is not working for me, so here's an updated recipe for anyone else experiencing that issue that wants a compact titlebar.

```less

.title-bar-replacer.control-theme-windows-10 {
  .tbr-title-bar {
    height: 2px;
    padding-top: 5px;
    padding-right: 2px;

    .custom-title { display: none; }
  }

  .control-wrap {
    i {
      margin: 2px;
      padding: 0 3px;
      font-size: 8px;
    }

    i:hover::before {
      width: 12px;
      height: 10px;
      top: -.8px;
      border-radius: 2.5px;
    }
  }
}

```
