### ISSUE TITLE
Remove Mouse Hover Effect?

### ISSUE THREAD

**Issue by heisbrot** [sindrets/atom-title-bar-replacer#18]
Hey,

could you add an option to remove the "pointer mouse" when you hover over close,minimize etc.
In Windows 10 the mouse does not change when you hover over these ;)
Otherwise love your work!

Best Regrads

**Comment by sindrets** [comment]
Hello @heisbrot! I'm glad you like my package. 
Styling can be very easily changed through Atom's Stylesheet `(File > Stylesheet)`. Adding something like this will give you your desired effect:
```less
.title-bar-replacer .tbr-title-bar .control-wrap {
    i, i:before {
        cursor: default;
    }
}
```
Or if you want it to only apply to the Windows 10 controls theme:
```less
.title-bar-replacer.control-theme-windows-10 .tbr-title-bar .control-wrap {
    i, i:before {
        cursor: default;
    }
}
```
There are unique css selectors for all appearence styles and controls themes specifically for this reason.
