### ISSUE TITLE
Change text size / style of menu bar and dropdowns?

### ISSUE THREAD

**Issue by 19lmyers** [sindrets/atom-title-bar-replacer#3]
I'm looking to remove the bold effect and make the text larger to match my UI text size. Could you add a setting for this?

**Comment by sindrets** [comment]
Hello @19lmyers! Thank's for the suggestion. However, I don't feel this is necessary, as these styles can be adjusted quite easily through Atom's stylesheet. If you're not familiar with Atom's stylesheet, it can be accessed from the menu:
* File > Stylesheet

Add the following snippet to the bottom, adjust the properties to whatever you'd like, save and restart Atom (restart is required to allow the title bar replacer to recalculate the position and size of the newly adjusted menu):

```css
.custom-menu {
    font-family: sans-serif;
    font-weight: 500;
    font-size: 14px;
}
```
